### PR TITLE
Makefile: TMUX_DIR with "./" prefix to ignore $CDPATH

### PR DESCRIPTION
**Pull request by blueyed**
Otherwise `cd` needs to be made silent, since it might output the dir it
changed to (bash does so for me), resulting in two lines of output and
the following error with `make`:

> sed: -e expression #1, char 17: unknown option to `s'

### CODE REVIEW

**Comment by ericpruitt** [comment]
There are 2-ish issues:

1. I've never seen any POSIX-compatible shell with a "cd" implementation that produces output when not used interactively, and I couldn't reproduce this problem with any shell on my computer:

    ~~~
    $ for shell in bash /bin/bash zsh dash "busybox sh"; do printf "%s: %s\n" "$shell -c 'cd /'" "$($shell -c 'cd /')"; done
    bash -c 'cd /':
    /bin/bash -c 'cd /':
    zsh -c 'cd /':
    dash -c 'cd /':
    busybox sh -c 'cd /':
    ~~~

2. The Makefile is POSIX compliant, and of the recipes use POSIX shell syntax. Make is supposed to use _sh(1)_ by default when executing recipes. Some Make implementations allow the user to change the shell, but as a user, you shouldn't expect other people's Makefiles to work if you're using some shell other than _sh(1)_ (or another shell configured to be POSIX-compliant i.e. "bash --posix", zsh symlinked to "sh", etc.) for recipes.

**Comment by blueyed** [comment]
It is related to `CDPATH`, and actually goes to another dir that it would expect.
I have `~/Vcs` in `$CDPATH` and there is a checkout of `tmux` also.

From `man dash`:

    cd [-LP] [directory]

    Switch to the specified directory (default HOME).  If an entry for CDPATH
    appears in the environment of the cd command or the shell variable CDPATH is
    set and the directory name does not begin with a slash, then the directories
    listed in CDPATH will be searched for the specified directory.  The format of
    CDPATH is the same as that of PATH.  If a single dash is specified as the
    argument, it will be replaced by the value of OLDPWD.  The cd command will
    print out the name of the directory that it actually switched to if this is
    different from the name that the user gave.  These may be different either
    because the CDPATH mechanism was used or because the argument is a single
    dash.  The -P option causes the physical directory structure to be used, that
    is, all symbolic links are resolved to their respective values.  The -L option
    turns off the effect of any preceding -P options.

What about using `$(CURDIR)` with `TMUX_GIT_DIR` to make it absolute?
Or just prefix it with `./`?
Amended.

**Comment by ericpruitt** [comment]
The CURDIR macro is a GNU-ism, and I want the Makefile to be portable. Using "./" also creates portability problems because not all Make implementations treat `./$FILENAME` and `$FILENAME` as the same target which means that people that aren't using GNU Make would have to make sure to add "./" when specifying a target as a command line argument. That aside, I think this problem is too esoteric to warrant making any changes to the Makefile. You can fix this on your end of things by only setting CDPATH interactively i.e. `alias cd='CDPATH="..." cd`.

**Comment by blueyed** [comment]
I see.  Thanks for the explanation.

I was setting it in `.zprofile` (mostly for performance reasons I guess) and exported it to be used with Vim/Neovim.
I am setting it now in zshrc and do not export it anymore.

FWIW: `set -p` (privileged mode) for Bash or unsetting `CDPATH` explicitly would be fixes for this issue.  Given my setup I've run into this several times already, but I agree that not exporting `CDPATH` is a good fix in general.

**Pull request closed without merging**
