### PR TITLE
readme: Remove duplicate word

### PR DESCRIPTION
**Pull request by polyzen**

### CODE REVIEW

**Comment by ericpruitt** [comment]
I understand why some people choose to, but I normally don't write commit messages in the form of "$TOPIC: $MESSAGE", so please remove "readme: " from the beginning of the commit message to be consistent with the rest of the changes in my project, and I'll merge this request.

**Comment by polyzen** [comment]
Fair enough.

**Comment by blueyed** [comment]
@ericpruitt 
Just for information: you can squash-merge single commits using Github's UI and then adjust the title and message of the commit.

**Comment by ericpruitt** [comment]
How? I tried to edit the message from the web interface, but I couldn't figure it out hence the sporadic title change earlier. I disabled "Allow merge commits" in the settings for this repository, but I made that change after accepting the pull request, so I'm not sure if it does what I expect it to do.

**Pull request merged**
